model_params:
  name: 'VanillaVAE'
  in_channels: 3
  latent_dim: 128


data_params:
  data_path: "/home/omer/Documents/Vinci/vinci_core/local_assets/Covers/10/"
  train_batch_size: 64
  val_batch_size:  64
  patch_size: 64
  num_workers: 4


exp_params:
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 1265

trainer_params:
  gpus: []
  max_epochs: 5

logging_params:
  save_dir: "logs/"
  name: "VanillaVAE"
  
